doctrine:
    dbal:
#        url: '%env(resolve:DATABASE_URL)%'
#        driver: '%env(resolve:DATABASE_DRIVER)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
#        schema_filter: ~^(?!public)~ # Exclude public schema from schema update (make:migration)
        #server_version: '16'

#        profiling_collect_backtrace: '%kernel.debug%'
#        use_savepoints: true
        default_connection: mysql # postgres or mysql,
        connections:
            mysql:
                driver: 'pdo_mysql'
                host: '%env(resolve:MYSQL_HOST)%'
                port: '%env(resolve:MYSQL_HOST_PORT)%'
                dbname: '%env(resolve:MYSQL_DB)%'
                user: '%env(resolve:MYSQL_USER)%'
                password: '%env(resolve:MYSQL_PASSWORD)%'
            postgres:
                driver: 'pdo_pgsql'
                host: '%env(resolve:POSTGRES_HOST)%'
                port: '%env(resolve:POSTGRES_HOST_PORT)%'
                dbname: '%env(resolve:POSTGRES_DB)%'
                user: '%env(resolve:POSTGRES_USER)%'
                password: '%env(resolve:POSTGRES_PASSWORD)%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
