controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
telegram_webhook:
    path: /tg-webhook
    controller: telegram_bot.webhook_controller
